"""
Fetch a list of all accounts with balances of either:
- Auxo, ARV or PRV in wallet
- PRV Staked
- ARV Locked
Excludes accounts with zero balances, such as pass-through smart contracts
"""
query AllAccounts {
  accounts(
    where: {
      or: [
        { ERC20balances_: { value_not: "0" } }
        { ARVLocks_: { auxoValue_not: "0" } }
        { PRVStakingBalances_: { value_not: "0" } }
      ]
    }
  ) {
    id
    ARVLocks {
      auxoValue
      arvValue
      lockedAt
      lockDuration
    }
    PRVStakingBalances {
      value
    }
    ERC20balances {
      value
      contract {
        id
        name
        symbol
      }
    }
  }
}
